### PR TITLE
Add Feature: Load checks from json or yaml file

### PR DESCRIPTION
**Pull request by brotandgames**
If you define `CIAO_CHECKS_LOAD_FROM_FILE` ENV variable by setting it to a valid file path like

* `$file_path.[json|yaml|yml]` eg. `CIAO_CHECKS_LOAD_FROM_FILE="/data/ciao/checks_input.json"` *(file must be available in filesystem or docker/kubernetes volume)*, 

you can load checks from this file by 

* visiting `/checks/admin`in the Web UI and using the *Load from file* button **or**
* calling the JSON endpoint like `curl -X GET -H "Content-type: application/json" /checks/load-from-file.json`.

Example files

`checks_input.json`

````json
[
    {
        "active": true,
        "name": "brotandgames.com",
        "cron": "* * * * *",
        "url": "https://brotandgames.com"
    },
    {
        "active": true,
        "name": "kubernete.sh",
        "cron": "*/15 * * * *",
        "url": "https://kubernete.sh"
    }
]
````

`checks_input.yaml`

````yaml
---
- active: true
  name: brotandgames.com
  cron: "* * * * *"
  url: https://brotandgames.com
- active: true
  name: kubernete.sh
  cron: "*/15 * * * *"
  url: https://kubernete.sh
````

### CODE REVIEW

**Comment by brotandgames** [comment]
@warmfusion Would this suit your needs concerning #5?

ciao Helm Chart needs to be enhanced with optional Kubernetes Volume/ConfigMap.

**Comment by brotandgames** [comment]
Web UI Preview

grafik

**Comment by warmfusion** [comment]
Would it be possible to have the loaded file be 'watched' for changes and trigger the reload call?

something like https://github.com/guard/listen might suit with a little refactoring where the service inits and wraps a guard around the file defined on the ENV path.

Loading from a file over a rest api doesn't feel very secure as you could ping any file. Also i'm not sure what that curl example does on the web ui preview.

**Comment by linuxbandit** [comment]
If I may add an idea (lmk if you'd rather have me open an issue on that), I suggest also to add the configuration being imported on container startup: if there are files present in a specific filesystem folder, then load them

This is similar to how mariadb or grafana load their configuration (see [the doc](https://hub.docker.com/_/mariadb))

> When a container is started for the first time, a new database with the specified name will be created and initialized with the provided configuration variables. Furthermore, it will execute files with extensions .sh, .sql and .sql.gz that are found in /docker-entrypoint-initdb.d. Files will be executed in alphabetical order. You can easily populate your mariadb services by mounting a SQL dump into that directory and provide custom images with contributed data. SQL files will be imported by default to the database specified by the MYSQL_DATABASE variable.

**Comment by linuxbandit** [comment]
Btw, your description is unclear to me: 
- from the first part, I get it that it is already as I just suggested;
- from the second part, it is my understanding that I need still go to admin area and click "load from file" (and I presume I can upload a file?)

Thanks for clarifying (and for ciao, it's amazing!)

**Comment by warmfusion** [comment]
I second @linuxbandit 's point about 'load the config on bootup'

The sequence I'd want is;

1. I create a container that includes Ciao and setup a ConfigMap or copy config into the volume
2. The container is started and without any action Ciao reads my config from the mounted volume and starts
3. I later modify the configuration on the volume and Ciao realises a change has occurred and re-loads the configuration file without any additional action from me

The use of the webhook is interesting, but makes the process complicated on a kubernetes system as the ConfigMap might be updated and has no mechanism to 'notify' the service other than a full restart of the pod which seems unnecessary (Also, in my particular case I don't have stateful storage so I'd actually lose my check state at the same time)

**Comment by linuxbandit** [comment]
Hello,

is there a waiting-for related to this PR? It'd be a great addition to ciao

**Comment by brotandgames** [comment]
@linuxbandit @warmfusion Could we chat about this feature in Gitter? It seems that there are some things to clarify.

**Comment by brotandgames** [comment]
Closed this PR because of inactivity.

**Pull request closed without merging**
